### ISSUE TITLE
[QUESTION] Less verbose way to retrieve records with responses

### ISSUE THREAD

**Issue by dvsrepo** [argilla-io/argilla-python#126]
The most common workflow for retrieving a dataset is to get the records "submitted" with responses.

While learning the new SDK, it took me a while to find a way to achieve this. 

```python
records = dataset.records(
    with_responses=True, 
    query=rg.Query(filter=rg.Filter([("status", "==", "submitted")]))
)
```
I like the syntax but I wonder:

1. Are there other ways to achieve this?
2. Would it be possible to have a simpler way to achieve this, given how frequent this workflow will be?

**Comment by dvsrepo** [comment]
@frascuchon @burtenshaw let's put this on hold until we gain more visibility into the new task distribution feat

**Comment by nataliaElv** [comment]
@dvsrepo @burtenshaw Should we move this issue over to `argilla` or do you think we can close it?

**Comment by dvsrepo** [comment]
i'd say we can close it
