### ISSUE TITLE
[DOCS] Failing example for updating records.

### ISSUE THREAD

**Issue by frascuchon** [argilla-io/argilla-python#193]
The code snippet example in [this section](https://argilla-io.github.io/argilla-python/dev/reference/argilla_sdk/datasets/dataset_records/#updating-records-in-a-dataset) is not working. The `id` attribute is expected as `UUID` but a `str` is provided.

**Comment by sdiazlor** [comment]
With the use of `id` instead of `external_id`, Now `id` can be both `UUID `and `str`, right?
