### ISSUE TITLE
[DOCS] Review `external_id` usages

### ISSUE THREAD

**Issue by frascuchon** [argilla-io/argilla-python#194]
Since we plan to "hide" the `external_id` record attribute, maybe make sense to review examples (as [this one](https://argilla-io.github.io/argilla-python/dev/how_to_guides/record/#update-records)) to use the `id` instead.

**Comment by burtenshaw** [comment]
@frascuchon Is this closed?

**Comment by frascuchon** [comment]
Yeah. Closing it
