### ISSUE TITLE
[DOCS] Expand docs automatic generation

### ISSUE THREAD

**Issue by burtenshaw** [argilla-io/argilla-python#201]
The current implementation of the documentation relies on manual references between the documentation markdown and code. 

The advantage of this is that we get executive control of the documentation and menus, which makes it easier to deliver and iterate on feedback. The disadvantage is that most code changes require documentation changes in markdown. Furthermore, the manual structure of the docs prevents us from using certain documentation features, like pagination (#172).

This is not an ideal long term solution so we should expand automation to improve developer comfort and efficiency.

These tickets are an attribute of automating and finalising the docs:
- #172

**Comment by nataliaElv** [comment]
@davidberenstein1957 @sdiazlor Was this issue solved or is this still open? And if so, do we want to tackle this for 2.0 or later?
