### ISSUE TITLE
[FEATURE] Allow updating record attributes via a Record class definition

### ISSUE THREAD

**Issue by burtenshaw** [argilla-io/argilla-python#226]
Currently, the field attribute of a record is not optional, so attributes like vectors and metadata cannot be updated alone. The user has to use a dictionary definition.

This should support flows like this:

```python
dataset.records.update(Record(vectors=[rg.Vector(...)]))
```

**Comment by frascuchon** [comment]
another approach to tackle this would be the functional way of updating:

```python
dataset.records(...).map(...).map(embedder).update()
```
