### ISSUE TITLE
docs: API reference

### ISSUE THREAD

**Issue by davidberenstein1957** [argilla-io/argilla-python#65]
This is rendered automatically within mkdocs but @burtenshaw had some ideas about structuring this for the SDK and @jfcalvo might help with the server.
```[tasklist]
### Tasks
- [x] API ref/SDK @burtenshaw @sdiazlor
- [ ] API ref/FastAPI @jfcalvo @sdiazlor
```

**Comment by burtenshaw** [comment]
@nataliaElv We should move the server docs issue over to the main argilla repo.
